### ISSUE TITLE
Needs localization

### ISSUE THREAD

**Issue by ButchDean** [MarquisdeGeek/humanize-time#1]
The phrases given are British, times are given differently in North America. For the examples given (UK -> NA):

quarter past midnight -> 15 after midnight
one minute to six A.M. -> 5 fifty-nine in the morning (although AM may be used)
12 minutes past 5 P.M. -> 12 after 5 in the evening (sometimes PM may be used here too)

Just an interesting minor. :)

**Comment by MarquisdeGeek** [comment]
Agreed. It would be a good. Send me a PR!

**Comment by ButchDean** [comment]
I have a long thanksgiving weekend. I'll get on it!

**Comment by ButchDean** [comment]
Sorry I never got round to it! :\
